# Generated by Django 3.2.4 on 2021-07-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(max_length=1024)),
                ('prod_title', models.CharField(max_length=1024)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Url', models.CharField(max_length=254)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cookware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(max_length=1024)),
                ('prod_title', models.CharField(max_length=1024)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Url', models.CharField(max_length=254)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crockery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(max_length=1024)),
                ('prod_title', models.CharField(max_length=1024)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Url', models.CharField(max_length=254)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(max_length=1024)),
                ('prod_title', models.CharField(max_length=1024)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Url', models.CharField(max_length=254)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homedecor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(max_length=1024)),
                ('prod_title', models.CharField(max_length=1024)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('Url', models.CharField(max_length=254)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
